name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build image Backend
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-app:latest ./springboot/app

      # 4️⃣ Push image Backend
      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-app:latest

      # 5️⃣ Build image Frontend
      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest ./angular-app

      # 6️⃣ Push image Frontend
      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest

      # 7️⃣ Test avec Docker Compose
      - name: Run Docker Compose
        run: |
          docker-compose up -d
          sleep 20
          docker ps

      # 8️⃣ Vérification des conteneurs
      - name: Check containers
        run: docker-compose ps