name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Build Spring Boot JAR
      - name: Build Backend with Maven
        run: |
          cd springboot/app
          mvn clean package -DskipTests

      # 4️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build Backend Image
      - name: Build Backend Image
        run: |
          docker build -t hazemjr/spring-app:latest ./springboot/app

      # 6️⃣ Push Backend Image
      - name: Push Backend Image
        run: |
          docker push hazemjr/spring-app:latest

      # 7️⃣ Build Frontend Image
      - name: Build Frontend Image
        run: |
          docker build -t hazemjr/angular-app:latest ./angular-app

      # 8️⃣ Push Frontend Image
      - name: Push Frontend Image
        run: |
          docker push hazemjr/angular-app:latest

      # 9️⃣ Test avec Docker Compose
      - name: Run Docker Compose
        run: |
          docker compose up -d
          sleep 20
          docker ps